application:
  name: ^project.artifactId^
  description: ^project.name^
  version: ^project.version^
server:
  port: 8080
spring:
  application:
    name: ^project.artifactId^
spring.kafka.bootstrap-servers: velomobile-01.srvs.cloudkafka.com:9094,velomobile-02.srvs.cloudkafka.com:9094,velomobile-03.srvs.cloudkafka.com:9094
spring.kafka.properties.security.protocol: SASL_SSL
spring.kafka.properties.sasl.mechanism: SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="li5jiphz" password="nqa9_PsDVN5Szgm6cT7rZwNnTyOfZei6";
spring.cloud.stream.bindings:
  user-sink:
    contentType: application/json
    destination: li5jiphz-user
  user-source:
    contentType: application/json
    destination: li5jiphz-user
    producer:
      partition-key-expression: headers['partitionKey']
logging:
  level:
    org.apache.kafka.clients.consumer.ConsumerConfig: ERROR
    org.apache.kafka.clients.admin.AdminClientConfig: ERROR
    org.apache.kafka.clients.producer.ProducerConfig: ERROR
---
spring:
  profiles: dev
logging:
  level:
    com.github.richygreat.microbankbff: DEBUG